services:
  - type: web
    name: tennis-backend
    dockerfilePath: tenisApp/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        value: jdbc:postgresql://dpg-d1hbvqvdiees738mk25g-a.frankfurt-postgres.render.com:5432/main_jyz5
      - key: DB_USERNAME
        value: admin
      - key: DB_PASSWORD
        value: mB3FL3kaT41fbVJYJF7dKxlrUS8Sk3N0