# PRODUCTION CONFIG (Render.com)
spring.datasource.url=jdbc:postgresql://dpg-d1hbvqvdiees738mk25g-a.frankfurt-postgres.render.com:5432/main_jyz5
spring.datasource.username=admin
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=straleb123@gmail.com
spring.mail.password=${GMAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.notification.email=krstulovic.marko@gmail.com